[workspace]
resolver = "2"
members = [
  "./build/rust/*",
  "./cmdargs-derive",
  "llib",
  "dispatcher",
]

[workspace.package]
authors = ["Kamil Cukrowski"]
version = "0.1.4"
edition = "2021"
license = "GPL-3.0-only"
repository = "https://github.com/Kamilcuk/l_builtin"

[workspace.dependencies]
cmdargs-derive = { path = "./cmdargs-derive/" }

syn = { version = "3.0.4", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
libc = "0.2"
thiserror = "2.0"
nix = "0.31"
rustix = { version = "1.1", features = ["param", "use-libc-auxv", "time"] }
mlua = { version = "0.10", features = ["lua51", "vendored"] }
smallvec = "1.15"
memmap2 = "0.9"
uucore = { git = "https://github.com/uutils/coreutils", package = "uucore", rev = "f66e155d80df3d82798324726e460675a02c5cd5" }
uu_ls = { git = "https://github.com/uutils/coreutils", package = "uu_ls", rev = "f66e155d80df3d82798324726e460675a02c5cd5" }
uu_stat = { git = "https://github.com/uutils/coreutils", package = "uu_stat", rev = "f66e155d80df3d82798324726e460675a02c5cd5" }
uu_dirname = { git = "https://github.com/uutils/coreutils", package = "uu_dirname", rev = "f66e155d80df3d82798324726e460675a02c5cd5" }
uu_rm = { git = "https://github.com/uutils/coreutils", package = "uu_rm", rev = "f66e155d80df3d82798324726e460675a02c5cd5" }
uu_tee = { git = "https://github.com/uutils/coreutils", package = "uu_tee", rev = "f66e155d80df3d82798324726e460675a02c5cd5" }
uu_sleep = { git = "https://github.com/uutils/coreutils", package = "uu_sleep", rev = "f66e155d80df3d82798324726e460675a02c5cd5" }
rkyv = "0.8"
regex = "1.11"
sed-rs = "2.0.0"
parse_duration = "2.1"
tar = "0.4"
zstd = "0.13"

# Dev dependencies
tempfile = "3.15"
pretty_assertions = "1.4"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true

[workspace.lints.rust]
dead_code = "allow"

[workspace.lints.clippy]
missing_safety_doc = "allow"
undocumented_unsafe_blocks = "allow"
