[package]
name = "cmdargs-derive"
description = "Derive macro for L_builtin command argument parsing"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true
