/*
 * L_builtin Multi-Version Dispatcher
 *
 * Single .so with all versioned modules embedded. At runtime,
 * detects the running bash version and dlopen's the matching module
 * from a memfd (no disk I/O at runtime).
 */

#define _GNU_SOURCE
#include <config.h>
#include <builtins.h>
#include <shell.h>

#include <dlfcn.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>

/* Bash version symbols (from shell.h, available at runtime) */
extern char *dist_version;
extern int patch_level;
extern int build_version;
extern char *release_status;

/* Forward declaration */
int l_entrypoint(struct word_list *list);

/* Bash builtin registration - exported for bash's `enable -f` */
static const char *const l_builtin_doc[] = {
    "L_builtin multi-version dispatcher.",
    "",
    "L_builtin <subcommand> [options] [args]",
    "",
    "Available subcommands:",
    "  version      Print build and bash version information",
    (char *)NULL
};

struct builtin L_builtin_struct = {
    "L_builtin",
    l_entrypoint,
    BUILTIN_ENABLED,
    (void *)l_builtin_doc,
    "L_builtin <subcommand> [options] [args]",
    0
};

/* Embedded .so blobs - generated by objcopy at build time */
#include "dispatcher_version_table.h"

typedef int (*entrypoint_t)(struct word_list*);

static void* handle = NULL;

static void* load_embedded_so(const char* version) {
    for (int i = 0; embedded_sos[i].version; i++) {
        if (strcmp(embedded_sos[i].version, version) == 0) {
            size_t size = embedded_sos[i].end - embedded_sos[i].start;
            if (size == 0) {
                fprintf(stderr, "L_builtin: embedded module for %s is empty\n", version);
                return NULL;
            }

            /* Create memfd and write blob */
            int fd = memfd_create("L_builtin_embedded", MFD_CLOEXEC);
            if (fd < 0) {
                perror("L_builtin: memfd_create");
                return NULL;
            }

            ssize_t written = write(fd, embedded_sos[i].start, size);
            if (written != (ssize_t)size) {
                perror("L_builtin: write to memfd");
                close(fd);
                return NULL;
            }

            /* dlopen from memfd via /proc/self/fd/ */
            char path[64];
            snprintf(path, sizeof(path), "/proc/self/fd/%d", fd);

            void* handle = dlopen(path, RTLD_NOW | RTLD_LOCAL);
            if (!handle) {
                fprintf(stderr, "L_builtin: dlopen(%s) failed: %s\n", version, dlerror());
                close(fd);
                return NULL;
            }

            return handle;
        }
    }
    return NULL;
}

static const char* get_runtime_bash_version(void) {
    static char version[16];
    int major = 0, minor = 0;

    if (dist_version) {
        major = atoi(dist_version);
    }
    minor = patch_level / 100;

    snprintf(version, sizeof(version), "%d.%d", major, minor);
    return version;
}

int l_entrypoint(struct word_list *list) {
    if (!handle) {
        const char* version = get_runtime_bash_version();
        handle = load_embedded_so(version);
        if (!handle) {
            fprintf(stderr, "L_builtin: no module for bash %s\n", version);
            return 1;
        }
    }

    entrypoint_t ep = (entrypoint_t)dlsym(handle, "l_entrypoint");
    if (!ep) {
        fprintf(stderr, "L_builtin: no l_entrypoint in module\n");
        return 1;
    }

    return ep(list);
}
