#!/usr/bin/env python3
"""Generate the "Subcommand Reference" section (and its TOC entries) of
README.md from `L_builtin <subcommand> -h` output.

Run it with::

    make readme                       # uses uv to provide markdown-it-py

or directly::

    uv run --with markdown-it-py scripts/gen_readme.py
    uv run --with markdown-it-py scripts/gen_readme.py \
        --so build/Debug/system/L_builtin.so \
        --bash build/bash/system/bash \
        --readme README.md

The whole Table-of-Contents block of subcommand bullets is regenerated by
parsing the assembled markdown bodies with ``markdown-it-py`` (a CommonMark
library) so anchors always match the rendered headings.  The bullet list is
written between ``<!-- TOC_GEN_START -->`` / ``<!-- TOC_GEN_END -->`` markers
and the per-command reference text is written between
``<!-- README_GEN_START -->`` / ``<!-- README_GEN_END -->`` markers.

Rules:
  * Every section title carries the ``L_builtin`` prefix, e.g.
    ``### `L_builtin lseek```.
  * ``core`` is a thin wrapper around Rust/uutils coreutils: only its own
    ``-h`` listing is emitted (no per-utility sub-sections).
  * ``ext`` is a wrapper around Bash's example loadables: its ``-h`` listing
    is emitted *and* the ``-h`` output of every child builtin (asort, basename,
    ...) is included as a sub-section.
  * Compound commands (shm, mutex, semaphore, barrier, fcntl, epoll, eventfd,
    timerfd) recurse one level: each child action gets a sub-section.
  * ``unittest`` (a dev-only internal) is skipped.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

from markdown_it import MarkdownIt


# Commands whose -h lists child actions that we recurse into automatically.
COMPOUND = {
    "shm", "mutex", "semaphore", "barrier",
    "fcntl", "epoll", "eventfd", "timerfd",
}
# Commands never emitted at all.
SKIP = {"unittest"}


def run_builtin(bash: str, so: str, args: str) -> str:
    """Run ``L_builtin <args>`` inside a fresh bash with the .so enabled."""
    prog = (
        f"enable -f {so} L_builtin\n"
        f"L_builtin {args} 2>&1\n"
        f"exit $?\n"
    )
    cp = subprocess.run(
        [bash, "-c", prog],
        capture_output=True,
        text=True,
        check=False,
    )
    return cp.stdout


def _extract_listing(text: str, header: str) -> list[str]:
    """Return subcommand names from a two-column ``Available subcommands:`` /
    ``Subcommands:`` listing found in *text*.

    Each entry is an indented line ``  name   description``; the block ends at
    the first blank line (after entries have started) or at the first
    non-indented content line.
    """
    idx = text.find(header)
    if idx == -1:
        return []
    region = text[idx + len(header):]
    names: list[str] = []
    entry_re = re.compile(r"^  (\S+)\s+(\S.*)$")
    for line in region.splitlines():
        if line.strip() == "":
            # End of the listing block once we've collected at least one entry.
            if names:
                break
            continue
        if not line.startswith("  "):
            # Unindented prose line: end of the listing.
            if names:
                break
            continue
        # Indented line: an entry starts with exactly two spaces + non-space.
        m = entry_re.match(line)
        if m:
            names.append(m.group(1))
        # Deeper-indented (3+ spaces) lines are descriptions / continuations.
    return names


def _help(b, so, cmd: str, *sub: str) -> str:
    """Fetch help text for ``L_builtin <cmd> <sub...> -h`` (fallback --help)."""
    target = " ".join([cmd, *sub])
    out = run_builtin(b, so, f"{target} -h")
    if not out.strip():
        out = run_builtin(b, so, f"{target} --help")
    return out


def _github_anchor(text: str) -> str:
    """GitHub-compatible heading anchor (matches github-slugger): lowercases,
    keeps word characters (incl. underscore), hyphen and space, drops the
    rest, then spaces -> hyphens.  Backticks are already stripped by caller."""
    t = text.lower().strip()
    t = re.sub(r"<[^>]+>", "", t)          # strip HTML
    t = re.sub(r"[^\w\- ]", "", t)         # keep word chars (incl _), hyphen, space
    t = re.sub(r"\s+", "-", t)            # spaces -> hyphen; underscores stay
    t = re.sub(r"-+", "-", t)
    return t.strip("-")


def build_parts(b, so) -> list[tuple[int, str, str]]:
    """Return a list of ``(level, title, help_text)`` tuples, in display order."""
    names = _extract_listing(run_builtin(b, so, "-h"), "Available subcommands:")
    parts: list[tuple[int, str, str]] = []

    for name in names:
        if name in SKIP:
            continue
        help_text = _help(b, so, name)
        if not help_text.strip():
            continue

        if name == "core":
            # Just the listing; do not recurse into coreutils utilities.
            parts.append((3, f"L_builtin {name}", help_text))
            continue

        if name == "ext":
            # Listing + the -h of every example builtin.
            parts.append((3, f"L_builtin {name}", help_text))
            for child in _extract_listing(help_text, "Available subcommands:"):
                child_help = _help(b, so, name, child)
                if child_help.strip():
                    parts.append((4, f"L_builtin {name} {child}", child_help))
            continue

        if name in COMPOUND:
            parts.append((3, f"L_builtin {name}", help_text))
            for child in _extract_listing(help_text, "Subcommands:"):
                child_help = _help(b, so, name, child)
                if child_help.strip():
                    parts.append((4, f"L_builtin {name} {child}", child_help))
            continue

        parts.append((3, f"L_builtin {name}", help_text))

    return parts


def render_body(parts: list[tuple[int, str, str]]) -> str:
    lines: list[str] = []
    for level, title, text in parts:
        lines.append(f"{'#' * level} `{title}`")
        lines.append("")
        lines.append("```")
        lines.append(text.rstrip())
        lines.append("```")
        lines.append("")
    return "\n".join(lines)


def build_whole_toc(markdown_text: str) -> str:
    """Build the *entire* Table of Contents from the full README markdown using
    ``markdown-it-py``.

    Every ``##``/``###``/``####`` heading (except the ``## Table of Contents``
    heading that contains this very TOC) becomes a bullet.  Nesting depth is
    derived from the heading level relative to the shallowest level present
    (normally h2), so h2 → no indent, h3 → two spaces, h4 → four spaces, etc.
    """
    md = MarkdownIt("commonmark")
    toks = md.parse(markdown_text)
    headings: list[tuple[int, str]] = []
    for i, t in enumerate(toks):
        if t.type != "heading_open":
            continue
        inline = toks[i + 1]
        text = inline.content.strip()
        disp = re.sub(r"^`+|`+$", "", text).strip("`")
        lvl = int(t.tag[1:])  # h1 -> 1, h2 -> 2 ...
        headings.append((lvl, disp))

    if not headings:
        return ""
    base = min(lvl for lvl, _ in headings)
    bullets: list[str] = []
    for lvl, disp in headings:
        indent = "  " * (lvl - base)
        bullets.append(f"{indent}- [{disp}](#{_github_anchor(disp)})")
    return "\n".join(bullets)


def generate(b, so) -> str:
    """Return the rendered Subcommand Reference markdown body (headings + help
    text, without the surrounding markers)."""
    parts = build_parts(b, so)
    return render_body(parts)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--so", default="build/Debug/system/L_builtin.so")
    ap.add_argument("--bash", default="build/bash/system/bash")
    ap.add_argument("--readme", default="README.md")
    args = ap.parse_args()

    bash = Path(args.bash).resolve()
    so = Path(args.so).resolve()
    readme = Path(args.readme).resolve()

    for label, p in (("bash", bash), ("L_builtin.so", so)):
        if not p.exists():
            print(f"error: {label} not found: {p} (run `make build`)", file=sys.stderr)
            return 2
    if not readme.exists():
        print(f"error: README not found: {readme}", file=sys.stderr)
        return 2

    text = readme.read_text()

    # --- Verify both marker pairs are present. ---
    checks = (
        ("TOC", r"<!-- TOC_GEN_START -->.*?<!-- TOC_GEN_END -->"),
        ("Subcommand Reference", r"<!-- README_GEN_START -->.*?<!-- README_GEN_END -->"),
    )
    for label, pat in checks:
        if not re.search(pat, text, re.S):
            print(
                f"error: README.md must contain {label} markers. "
                f"Add a pair of <!-- *_GEN_START --> / <!-- *_GEN_END --> "
                f"comment markers around the relevant README block.",
                file=sys.stderr,
            )
            return 2

    # --- Assemble the Subcommand Reference body first. ---
    body = generate(str(bash), str(so))
    body_block = (
        "<!-- README_GEN_START -->\n"
        "\n"
        "This section is **auto-generated** from `L_builtin <subcommand> -h`.\n"
        "Regenerate with `make readme` or `uv run --with markdown-it-py "
        "scripts/gen_readme.py`. Do not edit by hand between the markers.\n"
        "\n"
        + body
        + "\n<!-- README_GEN_END -->"
    )

    # --- Build the WHOLE table of contents from the README with the new body
    # inserted (parsed by markdown-it-py so anchors match the real headings). ---
    work = re.sub(
        r"<!-- README_GEN_START -->.*?<!-- README_GEN_END -->",
        body_block,
        text,
        flags=re.S,
        count=1,
    )
    whole_toc = build_whole_toc(work)
    toc_block = (
        "<!-- TOC_GEN_START -->\n"
        + whole_toc
        + "\n<!-- TOC_GEN_END -->"
    )

    # --- Splice both regenerated blocks back into the original README text. ---
    text = re.sub(
        r"<!-- TOC_GEN_START -->.*?<!-- TOC_GEN_END -->",
        toc_block,
        text,
        flags=re.S,
        count=1,
    )
    text = re.sub(
        r"<!-- README_GEN_START -->.*?<!-- README_GEN_END -->",
        body_block,
        text,
        flags=re.S,
        count=1,
    )

    readme.write_text(text)
    print(f"regenerated README TOC + Subcommand Reference in {readme}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
