#![allow(dead_code)]
#![allow(unused_imports)]

use std::ffi::{c_void, CStr, OsStr, OsString};
use std::fmt;
use std::fmt::Display;
use std::iter::Map;
use std::marker::PhantomData;
pub use std::ops::Deref;
pub use std::os::raw::{c_char, c_int};
use std::os::unix::ffi::OsStrExt;
use std::os::unix::ffi::OsStringExt;
use std::sync::OnceLock;

use crate::{beprintln, bprintln};

// Bash exit-code macros (from shell.h)
pub const EX_USAGE: c_int = 258; /* syntax error in usage */
pub const EX_NOTFOUND: c_int = 127; /* command not found */
pub const EXECUTION_SUCCESS: c_int = 0;
pub const EXECUTION_FAILURE: c_int = 1;

///////////////////////////////////////////////////////////////////////////
// Bash FFI bindings, generated by bindgen from bash_api_gen.h and placed at
// ${CMAKE_SOURCE_DIR}/generated_rust/bash_api_gen.rs by CMake (see the
// generate_bindgen step in CMakeLists.txt). This crate has no build.rs, so the
// path is referenced via CARGO_MANIFEST_DIR (the project root) rather than
// Cargo's OUT_DIR.
//
// This provides the opaque types (SHELL_VAR, ARRAY, HASH_TABLE, WORD_DESC,
// WORD_LIST, ...), the full `struct builtin`, and all extern "C" declarations
// (l_* wrappers from bash_api.c plus the bash entry points Rust calls).
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/generated_rust/bash_api_gen.rs"
));

/// The `struct builtin` from Bash's builtins.h, generated by bindgen, re-exported
/// under the idiomatic PascalCase name.
pub type Builtin = builtin;

///////////////////////////////////////////////////////////////////////////

/// RAII wrapper for C strings that need to be freed with `free()`
#[repr(transparent)]
pub struct CStringOwned(pub *mut c_char);

impl CStringOwned {
    #[inline]
    pub fn to_bytes(&self) -> impl AsRef<[u8]> {
        if self.0.is_null() {
            b""
        } else {
            unsafe { CStr::from_ptr(self.0).to_bytes() }
        }
    }
}

impl Drop for CStringOwned {
    #[inline]
    fn drop(&mut self) {
        unsafe { l_xfree(self.0 as *mut c_void) };
    }
}

///////////////////////////////////////////////////////////////////////////

/// Wrapper to track lifetimes of char pointers.
#[repr(transparent)]
pub struct Cpnt<'a>(*mut c_char, PhantomData<&'a c_char>);

impl<'a> Cpnt<'a> {
    pub const fn new(ptr: *mut c_char) -> Self {
        Self(ptr, PhantomData)
    }
    pub unsafe fn to_cstr(&self) -> &'a CStr {
        CStr::from_ptr(self.0)
    }
    pub unsafe fn to_bytes(&self) -> &'a [u8] {
        self.to_cstr().to_bytes()
    }
    pub unsafe fn to_str(&self) -> Result<&'a str, std::str::Utf8Error> {
        self.to_cstr().to_str()
    }
    pub const fn as_ptr(&self) -> *mut c_char {
        self.0
    }
    /// Compare the C string with a byte slice (excluding the null terminator).
    pub unsafe fn eq_bytes(&self, other: &[u8]) -> bool {
        self.to_bytes() == other
    }
    /// Compare the C string with a `&str` (excluding the null terminator).
    pub unsafe fn eq_str(&self, other: &str) -> bool {
        self.to_bytes() == other.as_bytes()
    }
    /// Compare the C string with a null-terminated string using `libc::strcmp`.
    /// The `other` must contain a null byte (e.g. `"--help\0"`).
    pub unsafe fn strcmp(&self, other: &str) -> bool {
        debug_assert!(
            other.as_bytes().last() == Some(&0),
            "strcmp: `other` must be null-terminated"
        );
        unsafe { libc::strcmp(self.0, other.as_ptr() as *const c_char) == 0 }
    }
}

impl<'a, 'b> PartialEq<&'b [u8]> for Cpnt<'a> {
    fn eq(&self, other: &&'b [u8]) -> bool {
        unsafe { self.to_bytes() == *other }
    }
}

impl<'a> PartialEq<&str> for Cpnt<'a> {
    fn eq(&self, other: &&str) -> bool {
        unsafe { self.to_bytes() == other.as_bytes() }
    }
}

impl<'a> fmt::Display for Cpnt<'a> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        if self.0.is_null() {
            return write!(f, "(null)");
        }
        unsafe {
            let bytes = self.to_bytes();
            let text = String::from_utf8_lossy(bytes);
            write!(f, "{text}")
        }
    }
}

///////////////////////////////////////////////////////////////////////////
/// WORD_LIST utilities

#[repr(transparent)]
pub struct WordListView<'a>(*mut WORD_LIST, PhantomData<&'a WORD_LIST>);

#[repr(transparent)]
#[derive(Clone)]
pub struct WordListIterCpnt<'a>(*mut WORD_LIST, PhantomData<&'a WORD_LIST>);

pub type WordListIterBytes<'a> = Map<WordListIterCpnt<'a>, fn(Cpnt<'a>) -> &'a [u8]>;

pub type WordListIterOsString<'a> = Map<WordListIterBytes<'a>, fn(&[u8]) -> OsString>;

impl<'a> WordListView<'a> {
    pub unsafe fn from_raw(head: *mut WORD_LIST) -> Self {
        Self(head, PhantomData)
    }
    pub fn iter(&self) -> WordListIterCpnt<'a> {
        WordListIterCpnt(self.0, PhantomData)
    }
    pub fn iter_bytes(&self) -> WordListIterBytes<'_> {
        self.iter().map(|c| unsafe { c.to_bytes() })
    }
    pub fn iter_osstring(&self) -> WordListIterOsString<'_> {
        self.iter_bytes().map(|s| OsString::from_vec(s.to_vec()))
    }
    pub const fn as_ptr(&self) -> *mut WORD_LIST {
        self.0
    }
    pub unsafe fn current(&self) -> Option<Cpnt<'a>> {
        self.iter().current()
    }
}

impl<'a> IntoIterator for WordListView<'a> {
    type Item = Cpnt<'a>;
    type IntoIter = WordListIterCpnt<'a>;
    fn into_iter(self) -> Self::IntoIter {
        self.iter()
    }
}

impl<'a> WordListIterCpnt<'a> {
    pub unsafe fn print(&self) {
        for i in self.clone() {
            println!("{i}");
        }
    }
    pub unsafe fn current(&self) -> Option<Cpnt<'a>> {
        if !self.0.is_null() {
            // Direct field access on the (non-opaque) WORD_LIST/WORD_DESC
            // layouts generated by bindgen; no C shim needed.
            let word_ptr = (*self.0).word;
            if !word_ptr.is_null() {
                let pnt = (*word_ptr).word;
                if !pnt.is_null() {
                    return Some(Cpnt::new(pnt));
                }
            }
        }
        None
    }
    pub unsafe fn advance(&mut self) {
        if !self.0.is_null() {
            self.0 = (*self.0).next;
        }
    }
    pub const fn as_ptr(&self) -> *mut WORD_LIST {
        self.0
    }
}

impl<'a> Iterator for WordListIterCpnt<'a> {
    type Item = Cpnt<'a>;
    fn next(&mut self) -> Option<Self::Item> {
        unsafe {
            let item = self.current();
            self.advance();
            item
        }
    }
}

#[repr(transparent)]
pub struct WordListOwned(pub *mut WORD_LIST);

impl WordListOwned {
    pub fn as_view(&self) -> WordListView<'_> {
        unsafe { WordListView::from_raw(self.0) }
    }
    pub fn iter(&self) -> WordListIterCpnt<'_> {
        self.as_view().iter()
    }
}

impl Default for WordListOwned {
    fn default() -> Self {
        Self(std::ptr::null_mut())
    }
}

impl Drop for WordListOwned {
    fn drop(&mut self) {
        if !self.0.is_null() {
            unsafe { dispose_words(self.0) }
        }
    }
}

impl<'a> IntoIterator for &'a WordListOwned {
    type Item = Cpnt<'a>;
    type IntoIter = WordListIterCpnt<'a>;
    fn into_iter(self) -> Self::IntoIter {
        self.iter()
    }
}
