#![allow(dead_code)]
#![allow(unused_imports)]

use std::ffi::{c_void, CStr, OsStr, OsString};
use std::fmt;
use std::fmt::Display;
use std::iter::Map;
use std::marker::PhantomData;
pub use std::ops::Deref;
pub use std::os::raw::{c_char, c_int};
use std::os::unix::ffi::OsStrExt;
use std::os::unix::ffi::OsStringExt;
use std::sync::OnceLock;

use crate::bprint_bytes::BDisplay;
use crate::{beprintln, bprintln};

///////////////////////////////////////////////////////////////////////////
// Bash FFI bindings, generated by bindgen from bash_api_gen.h and placed at
// ${CMAKE_SOURCE_DIR}/generated_rust/bash_api_gen.rs by CMake (see the
// generate_bindgen step in CMakeLists.txt). This crate has no build.rs, so the
// path is referenced via CARGO_MANIFEST_DIR (the project root) rather than
// Cargo's OUT_DIR.
//
// This provides the opaque types (SHELL_VAR, ARRAY, HASH_TABLE, WORD_DESC,
// WORD_LIST, ...), the full `struct builtin`, and all extern "C" declarations
// (l_* wrappers from bash_api.c plus the bash entry points Rust calls).
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/generated_rust/bash_api_gen.rs"
));

/// The `struct builtin` from Bash's builtins.h, generated by bindgen, re-exported
/// under the idiomatic PascalCase name.
pub type Builtin = builtin;

/// this_command_name as rust slice
pub fn this_cmd_name() -> &'static [u8] {
    let ptr = unsafe { this_command_name };
    // debug_assert!(!ptr.is_null(), "this_command_name should never be NULL");
    if ptr.is_null() {
        c"".to_bytes()
    } else {
        unsafe { CStr::from_ptr(ptr).to_bytes() }
    }
}

///////////////////////////////////////////////////////////////////////////

/// RAII wrapper for C strings that need to be freed with `free()`
#[repr(transparent)]
pub struct CStringOwned(pub *mut c_char);

impl CStringOwned {
    #[inline]
    pub fn to_bytes(&self) -> impl AsRef<[u8]> {
        if self.0.is_null() {
            b""
        } else {
            unsafe { CStr::from_ptr(self.0).to_bytes() }
        }
    }
}

impl Drop for CStringOwned {
    #[inline]
    fn drop(&mut self) {
        unsafe { l_xfree(self.0 as *mut c_void) };
    }
}

///////////////////////////////////////////////////////////////////////////

/// Wrapper to track lifetimes of char pointers.
#[repr(transparent)]
pub struct Cpnt<'a>(*mut c_char, PhantomData<&'a c_char>);

impl<'a> Cpnt<'a> {
    pub const fn new(ptr: *mut c_char) -> Self {
        Self(ptr, PhantomData)
    }
    pub unsafe fn as_cstr(&self) -> &'a CStr {
        CStr::from_ptr(self.0)
    }
    pub unsafe fn as_bytes(&self) -> &'a [u8] {
        self.as_cstr().to_bytes()
    }
    pub unsafe fn as_str(&self) -> Result<&'a str, std::str::Utf8Error> {
        self.as_cstr().to_str()
    }
    pub const fn as_ptr(&self) -> *mut c_char {
        self.0
    }
    pub const fn as_mut_ptr(&self) -> *mut c_char {
        self.0
    }
    /// Compare the C string with a byte slice (excluding the null terminator).
    pub unsafe fn eq_bytes(&self, other: &[u8]) -> bool {
        self.as_bytes() == other
    }
    /// Compare the C string with a `&str` (excluding the null terminator).
    pub unsafe fn eq_str(&self, other: &str) -> bool {
        self.as_bytes() == other.as_bytes()
    }
    /// Compare the C string with a null-terminated string using `libc::strcmp`.
    /// The `other` must contain a null byte (e.g. `"--help\0"`).
    pub unsafe fn strcmp(&self, other: &str) -> bool {
        debug_assert!(
            other.as_bytes().last() == Some(&0),
            "strcmp: `other` must be null-terminated"
        );
        unsafe { libc::strcmp(self.0, other.as_ptr() as *const c_char) == 0 }
    }
}

impl<'a, 'b> PartialEq<&'b [u8]> for Cpnt<'a> {
    fn eq(&self, other: &&'b [u8]) -> bool {
        unsafe { self.as_bytes() == *other }
    }
}

impl<'a> PartialEq<&str> for Cpnt<'a> {
    fn eq(&self, other: &&str) -> bool {
        unsafe { self.as_bytes() == other.as_bytes() }
    }
}

impl<'a> fmt::Display for Cpnt<'a> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        if self.0.is_null() {
            return write!(f, "(null)");
        }
        unsafe {
            let bytes = self.as_bytes();
            let text = String::from_utf8_lossy(bytes);
            write!(f, "{text}")
        }
    }
}

impl<'a> BDisplay for Cpnt<'a> {
    fn bwrite<W: std::io::Write>(&self, w: &mut W) {
        w.write_all(unsafe { self.as_bytes() }).ok();
    }
}

///////////////////////////////////////////////////////////////////////////
// WORD_LIST utilities

#[repr(transparent)]
pub struct WordListView<'a>(*mut WORD_LIST, PhantomData<&'a WORD_LIST>);

#[repr(transparent)]
#[derive(Clone)]
pub struct WordListIterCpnt<'a>(*mut WORD_LIST, PhantomData<&'a WORD_LIST>);

pub type WordListIterBytes<'a> = Map<WordListIterCpnt<'a>, fn(Cpnt<'a>) -> &'a [u8]>;

pub type WordListIterOsString<'a> = Map<WordListIterBytes<'a>, fn(&[u8]) -> OsString>;

impl<'a> WordListView<'a> {
    pub unsafe fn from_raw(head: *mut WORD_LIST) -> Self {
        Self(head, PhantomData)
    }
    pub fn iter(&self) -> WordListIterCpnt<'a> {
        WordListIterCpnt(self.0, PhantomData)
    }
    pub fn iter_bytes(&self) -> WordListIterBytes<'_> {
        self.iter().map(|c| unsafe { c.as_bytes() })
    }
    pub fn iter_osstring(&self) -> WordListIterOsString<'_> {
        self.iter_bytes().map(|s| OsString::from_vec(s.to_vec()))
    }
    pub const fn as_ptr(&self) -> *mut WORD_LIST {
        self.0
    }
    pub unsafe fn current(&self) -> Option<Cpnt<'a>> {
        self.iter().current()
    }
}

impl<'a> IntoIterator for WordListView<'a> {
    type Item = Cpnt<'a>;
    type IntoIter = WordListIterCpnt<'a>;
    fn into_iter(self) -> Self::IntoIter {
        self.iter()
    }
}

impl<'a> WordListIterCpnt<'a> {
    pub unsafe fn print(&self) {
        for i in self.clone() {
            println!("{i}");
        }
    }
    pub unsafe fn current(&self) -> Option<Cpnt<'a>> {
        if !self.0.is_null() {
            // Direct field access on the (non-opaque) WORD_LIST/WORD_DESC
            // layouts generated by bindgen; no C shim needed.
            let word_ptr = (*self.0).word;
            if !word_ptr.is_null() {
                let pnt = (*word_ptr).word;
                if !pnt.is_null() {
                    return Some(Cpnt::new(pnt));
                }
            }
        }
        None
    }
    pub unsafe fn advance(&mut self) {
        if !self.0.is_null() {
            self.0 = (*self.0).next;
        }
    }
    pub const fn as_ptr(&self) -> *mut WORD_LIST {
        self.0
    }
}

impl<'a> Iterator for WordListIterCpnt<'a> {
    type Item = Cpnt<'a>;
    fn next(&mut self) -> Option<Self::Item> {
        unsafe {
            let item = self.current();
            self.advance();
            item
        }
    }
}

#[repr(transparent)]
pub struct WordListOwned(pub *mut WORD_LIST);

impl WordListOwned {
    pub fn as_view(&self) -> WordListView<'_> {
        unsafe { WordListView::from_raw(self.0) }
    }
    pub fn iter(&self) -> WordListIterCpnt<'_> {
        self.as_view().iter()
    }
}

impl Default for WordListOwned {
    fn default() -> Self {
        Self(std::ptr::null_mut())
    }
}

impl Drop for WordListOwned {
    fn drop(&mut self) {
        if !self.0.is_null() {
            unsafe { dispose_words(self.0) }
        }
    }
}

impl<'a> IntoIterator for &'a WordListOwned {
    type Item = Cpnt<'a>;
    type IntoIter = WordListIterCpnt<'a>;
    fn into_iter(self) -> Self::IntoIter {
        self.iter()
    }
}

/// Check if a byte slice is a valid bash variable name.
/// Valid names: [a-zA-Z_][a-zA-Z0-9_]*
pub fn is_valid_var_name(name: &[u8]) -> bool {
    if name.is_empty() {
        return false;
    }
    let first = name[0];
    if !first.is_ascii_alphabetic() && first != b'_' {
        return false;
    }
    for &ch in &name[1..] {
        if !ch.is_ascii_alphanumeric() && ch != b'_' {
            return false;
        }
    }
    true
}

#[cfg(any(feature = "dev", test))]
pub(crate) mod tests {
    use super::*;

    crate::unittest_test! {
        fn test_valid_var_names() {
            assert!(is_valid_var_name(b"VAR"));
            assert!(is_valid_var_name(b"var"));
            assert!(is_valid_var_name(b"_var"));
            assert!(is_valid_var_name(b"var123"));
            assert!(is_valid_var_name(b"_"));
            assert!(is_valid_var_name(b"VAR_123"));
        }
    }

    crate::unittest_test! {
        fn test_invalid_var_names() {
            assert!(!is_valid_var_name(b""));
            assert!(!is_valid_var_name(b"123var"));
            assert!(!is_valid_var_name(b"var-name"));
            assert!(!is_valid_var_name(b"var.name"));
            assert!(!is_valid_var_name(b"var name"));
            assert!(!is_valid_var_name(b"-var"));
        }
    }
}

///////////////////////////////////////////////////////////////////////////
// Bash ARRAY / HASH_TABLE iterators

/// Iterate over a bash indexed array, yielding `(index, value)` pairs. The
/// value is a NUL-terminated `CStr` (or the empty NUL string when the element
/// is null).
pub struct ArrayIterator {
    head: *mut ARRAY_ELEMENT,
    current: *mut ARRAY_ELEMENT,
}

impl ArrayIterator {
    pub unsafe fn new(arr: *mut ARRAY) -> Self {
        let head = l_array_head(arr);
        Self {
            head,
            current: if head.is_null() {
                std::ptr::null_mut()
            } else {
                l_element_forw(head)
            },
        }
    }
}

impl Iterator for ArrayIterator {
    type Item = (i64, &'static CStr);

    fn next(&mut self) -> Option<Self::Item> {
        if self.current == self.head {
            return None;
        }
        unsafe {
            let idx = l_element_index(self.current);
            let val = l_element_value(self.current);
            let cstr = if val.is_null() {
                c""
            } else {
                CStr::from_ptr(val)
            };
            self.current = l_element_forw(self.current);
            Some((idx, cstr))
        }
    }
}

/// Iterate over a bash associative array, yielding `(key, value)` pairs. Both
/// keys and values are NUL-terminated `CStr`s (or the empty NUL string when
/// null).
pub struct AssocIterator {
    keys_list: *mut WORD_LIST,
    current: *mut WORD_LIST,
    hash: *mut HASH_TABLE,
}

impl AssocIterator {
    pub unsafe fn new(hash: *mut HASH_TABLE) -> Self {
        let keys = assoc_keys_to_word_list(hash);
        Self {
            keys_list: keys,
            current: keys,
            hash,
        }
    }
}

impl Iterator for AssocIterator {
    type Item = (&'static CStr, &'static CStr);

    fn next(&mut self) -> Option<Self::Item> {
        while !self.current.is_null() {
            unsafe {
                let wl = self.current;
                self.current = (*wl).next;
                let word_ptr = (*wl).word;
                if word_ptr.is_null() {
                    continue;
                }
                let key_ptr = (*word_ptr).word;
                if key_ptr.is_null() {
                    continue;
                }
                let key_cstr = CStr::from_ptr(key_ptr);
                let val_ptr = assoc_reference(self.hash, key_ptr);
                let val_cstr = if val_ptr.is_null() {
                    c""
                } else {
                    CStr::from_ptr(val_ptr)
                };
                return Some((key_cstr, val_cstr));
            }
        }
        None
    }
}

impl Drop for AssocIterator {
    fn drop(&mut self) {
        if !self.keys_list.is_null() {
            unsafe {
                dispose_words(self.keys_list);
            }
        }
    }
}

#[macro_export]
macro_rules! l_builtin_error {
    ( $( $arg:expr ),+ $(,)? ) => {
        {
            $crate::beprintln!($crate::bash_api::this_cmd_name(), b": error: ", $( $arg ),+);
            $crate::bash_api::EXECUTION_FAILURE
        }
    };
}

#[macro_export]
macro_rules! l_builtin_warning {
    ( $( $arg:expr ),+ $(,)? ) => {
        $crate::beprintln!($crate::bash_api::this_cmd_name(), b": warning: ", $( $arg ),+)
    };
}

pub(crate) fn l_builtin_usage() {
    let short_doc = unsafe {
        if current_builtin.is_null() || (*current_builtin).short_doc.is_null() {
            c"".as_ptr() as *const c_char
        } else {
            (*current_builtin).short_doc
        }
    };
    beprintln!(this_cmd_name(), ": usage: ", short_doc);
}

#[macro_export]
macro_rules! l_builtin_usage_error {
    ( $( $arg:expr ),+ $(,)? ) => {
        {
            $crate::l_builtin_error!($( $arg ),+);
            $crate::bash_api::l_builtin_usage();
            EX_USAGE
        }
    };
}
