use crate::bash_api::{c_char, c_int, Cpnt, WordListView, WORD_LIST};

pub const GETOPT_HELP: c_int = -99;

// internal_getopt, reset_internal_getopt, list_optarg and loptend are
// generated by bindgen in build.rs from bashgetopt.h (via bash_api_gen.h).
// Re-exported here so `$crate::bash_getopt::*` paths in the macros resolve.
pub use crate::bash_api::{internal_getopt, list_optarg, loptend, reset_internal_getopt};

/// Check whether `loptend` points to `--help`; if so, call
/// [`crate::bash_api::l_builtin_usage_long`] and return `true`. The caller
/// should return `EX_USAGE`.
pub unsafe fn check_help() -> bool {
    if let Some(next) = unsafe { WordListView::from_raw(loptend).current() } {
        if unsafe { next.strcmp("--help\0") } {
            crate::bash_api::l_builtin_usage_long();
            return true;
        }
    }
    false
}

/// One item returned by [`BashGetopt::next`].
pub enum GetoptItem {
    /// A valid option character.
    Opt(c_int),
    /// End of options.
    Done,
    /// An error occurred (invalid option, `-h`, or `--help`).
    /// `builtin_usage()` has already been called for `-h`/`--help`.
    Err(c_int),
}

impl GetoptItem {
    /// Unwrap the option character, or call `on_err` with the error code.
    /// `on_err` is expected to return from the enclosing function
    /// (e.g. `|e| return e`).
    pub fn unwrap(self, on_err: impl FnOnce(c_int) -> c_int) -> Option<c_int> {
        match self {
            GetoptItem::Opt(c) => Some(c),
            GetoptItem::Done => None,
            GetoptItem::Err(e) => {
                on_err(e);
                unreachable!()
            }
        }
    }
}

/// Iterator-style wrapper around bash's `internal_getopt`.
///
/// Created by [`BashGetopt::new`], yields [`GetoptItem`] values via
/// [`BashGetopt::next`]. Handles `-h` and `--help` automatically by calling
/// `builtin_usage()`.
pub struct BashGetopt {
    list: *mut WORD_LIST,
    optstring: *const c_char,
    /// Set once `internal_getopt` returned `-1`; compiled into debug builds
    /// only, where calling `next()` after `Done` asserts. Absent in release
    /// builds.
    #[cfg(debug_assertions)]
    done: bool,
}

impl BashGetopt {
    /// Create a new `BashGetopt` and call `reset_internal_getopt()`.
    pub fn new(list: *mut WORD_LIST, optstring: &[u8]) -> Self {
        unsafe { reset_internal_getopt() };
        BashGetopt {
            list,
            optstring: optstring.as_ptr() as *const c_char,
            #[cfg(debug_assertions)]
            done: false,
        }
    }

    /// Return the next option, or `Done`/`Err`.
    pub fn next(&mut self) -> GetoptItem {
        #[cfg(debug_assertions)]
        debug_assert!(
            !self.done,
            "BashGetopt::next called after options exhausted"
        );
        if unsafe { check_help() } {
            return GetoptItem::Err(crate::bash_api::EX_USAGE);
        }
        let c = unsafe { internal_getopt(self.list, self.optstring as *mut c_char) };
        match c {
            -1 => {
                #[cfg(debug_assertions)]
                {
                    self.done = true;
                }
                GetoptItem::Done
            }
            GETOPT_HELP => {
                unsafe { crate::bash_api::builtin_usage() };
                GetoptItem::Err(crate::bash_api::EX_USAGE)
            }
            c if c == b'h' as c_int => {
                unsafe { crate::bash_api::builtin_usage() };
                GetoptItem::Err(crate::bash_api::EX_USAGE)
            }
            c => GetoptItem::Opt(c),
        }
    }

    /// Return the optarg for the current option.
    pub fn optarg(&self) -> Cpnt<'static> {
        unsafe { Cpnt::new(list_optarg) }
    }

    /// Return the remaining words after option parsing.
    pub fn remaining(&self) -> *mut WORD_LIST {
        unsafe { loptend }
    }
}

/// Takes WORD_LIST, a function printing help message, and then flag letters and options letters.
/// Returns an object that for flag letters have the letters as members as bool
/// and for options letters has those letters as Option<*c_char>.
#[macro_export]
macro_rules! bash_getopt {
    (
        $list:expr,
        $help_fn:expr,
        [ $( $flag:ident ),* $(,)? ],
        [ $( $opt:ident ),* $(,)? ] $(,)?
    ) => {{
        const OPTSTRING: &[u8] = concat!(
            $( stringify!($flag), )*
            $( stringify!($opt), ":", )*
            "h\0",
        ).as_bytes();
        struct ParsedOpts {
            $( pub $flag: bool, )*
            $( pub $opt: Option<*mut std::os::raw::c_char>, )*
        }
        #[allow(unused_mut)]
        let mut parsed = ParsedOpts {
            $( $flag: false, )*
            $( $opt: None, )*
        };
        $crate::bash_getopt::reset_internal_getopt();
        let list = $list;
        loop {
            let c = unsafe {
                $crate::bash_getopt::internal_getopt(
                    list,
                    OPTSTRING.as_ptr().cast::<std::os::raw::c_char>().cast_mut(),
                )
            };
            match c {
                -1 => break,
                c if c == b'h' as std::os::raw::c_int => { $help_fn(); return 0; }
                $crate::bash_getopt::GETOPT_HELP => { $help_fn(); return 2; },
                $(
                    c if c == stringify!($flag).as_bytes()[0] as std::os::raw::c_int => {
                        parsed.$flag = true;
                    }
                )*
                $(
                    c if c == stringify!($opt).as_bytes()[0] as std::os::raw::c_int => {
                        parsed.$opt = Some(unsafe { $crate::bash_getopt::list_optarg.cast() });
                    }
                )*
                _ => return EX_USAGE,
            }
        };
        (parsed, $crate::bash_getopt::loptend)
    }};
}

/// Specifies the arity of a positional argument.
///
/// Each variant carries the argument's name as a `&'static str` (produced by
/// [`parse_positional_spec!`] via `stringify!` — zero allocation).
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PositionalSpec {
    /// Must be present exactly once.
    Required(&'static str),
    /// May be absent; produces `Option<Cpnt>`.
    Optional(&'static str),
    /// Consumes all remaining words (may be empty); produces `Vec<Cpnt>`.
    ZeroOrMore(&'static str),
    /// Consumes all remaining words (must be at least one); produces `Vec<Cpnt>`.
    OneOrMore(&'static str),
}

impl PositionalSpec {
    /// Return the name of this positional argument.
    pub fn name(&self) -> &'static str {
        match self {
            PositionalSpec::Required(n)
            | PositionalSpec::Optional(n)
            | PositionalSpec::ZeroOrMore(n)
            | PositionalSpec::OneOrMore(n) => n,
        }
    }
}

/// Validate positional specs at compile time: variadic (`*`, `+`) must be last,
/// and no required argument may follow an optional one.
pub const fn validate_positional_specs(specs: &[PositionalSpec]) -> Option<&'static str> {
    let mut seen_optional = false;
    let mut i = 0;

    while i < specs.len() {
        match specs[i] {
            PositionalSpec::Required(_) => {
                if seen_optional {
                    return Some(
                        "required positional argument cannot follow optional positional argument",
                    );
                }
            }
            PositionalSpec::Optional(_) => {
                seen_optional = true;
            }
            PositionalSpec::ZeroOrMore(_) | PositionalSpec::OneOrMore(_) => {
                if i != specs.len() - 1 {
                    return Some(
                        "variadic positional argument ('*' or '+') must be the last positional argument",
                    );
                }
            }
        }
        i += 1;
    }
    None
}

/// Returns `true` if any positional spec is variadic (`*` or `+`).
pub const fn has_variadic(specs: &[PositionalSpec]) -> bool {
    let mut i = 0;
    while i < specs.len() {
        match specs[i] {
            PositionalSpec::ZeroOrMore(_) | PositionalSpec::OneOrMore(_) => return true,
            _ => {}
        }
        i += 1;
    }
    false
}

/// Convert a positional-spec token into a [`PositionalSpec`] variant.
///
/// | Syntax   | Variant       | Type produced              |
/// |----------|---------------|----------------------------|
/// | `name`   | `Required`    | `Cpnt`              |
/// | `name?`  | `Optional`    | `Option<Cpnt>`      |
/// | `name*`  | `ZeroOrMore`  | `Vec<Cpnt>`         |
/// | `name+`  | `OneOrMore`   | `Vec<Cpnt>`         |
#[macro_export]
macro_rules! parse_positional_spec {
    ($name:ident (,)?) => {
        $crate::bash_getopt::PositionalSpec::Required(stringify!($name))
    };
    ($name:ident ?) => {
        $crate::bash_getopt::PositionalSpec::Optional(stringify!($name))
    };
    ($name:ident *) => {
        $crate::bash_getopt::PositionalSpec::ZeroOrMore(stringify!($name))
    };
    ($name:ident +) => {
        $crate::bash_getopt::PositionalSpec::OneOrMore(stringify!($name))
    };
}

/// Internal helper: parse a single positional value from the remaining-words
/// iterator. Dispatches on the modifier token.
#[macro_export]
macro_rules! bash_getopt2_parse_positional {
    // Required (no modifier)
    ($iter:expr, $name:ident) => {
        match $iter.next() {
            Some(v) => v,
            None => {
                $crate::beprintln!(
                    $crate::bash_api::this_command_name,
                    ": missing required argument '",
                    stringify!($name),
                    "'"
                );
                return $crate::bash_api::EX_USAGE;
            }
        }
    };
    // Optional (`?`)
    ($iter:expr, $name:ident ?) => {
        $iter.next()
    };
    // Zero-or-more (`*`)
    ($iter:expr, $name:ident *) => {
        $iter.collect();
    };
    // One-or-more (`+`)
    ($iter:expr, $name:ident +) => {
        let vec = $iter.collect();
        if $name.is_empty() {
            $crate::beprintln!(
                $crate::bash_api::this_command_name,
                ": '",
                stringify!($name),
                "' requires at least one argument"
            );
            return $crate::bash_api::EX_USAGE;
        }
        vec
    };
}

#[macro_export]
macro_rules! getopts_colon {
    (:) => {
        ":"
    };
    () => {
        ""
    };
}

/// Parse options from a bash `WORD_LIST` using bash's `internal_getopt`.
///
/// Automatically adds `-h` which calls bash's `builtin_usage()` and returns
/// `EX_USAGE`. The `-h` flag is appended to the optstring automatically — do
/// not add it manually.
///
/// # Syntax
///
/// ```ignore
/// let rest = getopts!(
///     list,                                // *mut WORD_LIST
///     [
///         e: => |val| env_var = Some(val), // option taking an argument (: suffix)
///         f  => || force = true,           // flag (no colon)
///     ]
/// );
/// ```
///
/// **Option actions** for flags (`f`) are called with no arguments (`||`).
/// For value options (`e:`), the action receives `Cpnt` (the optarg).
///
/// Returns the remaining-words pointer (`loptend`), the words after the end
/// of options. Feed it to [`parse_positionals!`].
///
/// On error prints using bash's help machinery and returns `EX_USAGE` from the
/// enclosing function.
#[macro_export]
macro_rules! getopts {
    (
        $args:expr,
        [ $( $flag:ident => $flag_action:expr ),* $(,)? ],
        [ $( $opt:ident => $opt_action:expr ),* $(,)? ] $(,)?
    ) => {{
        $crate::bash_getopt::reset_internal_getopt();
        let list = $args;
        const OPTSTRING: &[u8] = concat!(
            $( stringify!($flag), )*
            $( stringify!($opt), ":", )*
            "h\0"
        ).as_bytes();
        loop {
            if unsafe { $crate::bash_getopt::check_help() } {
                return $crate::bash_api::EX_USAGE;
            }
            let c = unsafe {
                $crate::bash_getopt::internal_getopt(
                    list,
                    OPTSTRING.as_ptr().cast::<std::os::raw::c_char>().cast_mut(),
                )
            };
            match c {
                -1 => break,
                $crate::bash_getopt::GETOPT_HELP | 104 /* 'h' */ => {
                    $crate::bash_api::l_builtin_usage_long();
                    return $crate::bash_api::EX_USAGE;
                }
                $(
                    c if c == stringify!($flag).as_bytes()[0] as std::os::raw::c_int => {
                        $flag_action();
                    }
                )*
                $(
                    c if c == stringify!($opt).as_bytes()[0] as std::os::raw::c_int => {
                        $opt_action(unsafe { $crate::bash_api::Cpnt::new($crate::bash_api::list_optarg) });
                    }
                )*
                _ => return $crate::bash_api::EX_USAGE,
            }
        }
        unsafe { $crate::bash_getopt::loptend }
    }};
}

/// Parse positional arguments from the words remaining after option parsing.
///
/// # Syntax
///
/// ```ignore
/// let (src, dest, files) = parse_positionals!(rest, [ src, dest?, files* ]);
/// let (src, files) = parse_positionals!(rest, [src], +files);
/// let (src, mode, files) = parse_positionals!(rest, [src], [mode], *files);
/// let (src, mode, files) = parse_positionals!(rest, [src], [mode], +files);
/// ```
///
/// **Positional modifiers** control arity:
/// - `<ident>`   — required → `Cpnt` (missing → `EX_USAGE`)
/// - `<ident>?`  — optional → `Option<Cpnt>`
/// - `<ident>*`  — zero or more → `Vec<Cpnt>`
/// - `<ident>+`  — one or more → `Vec<Cpnt>` (empty → `EX_USAGE`)
///
/// Following the `*`/`+` modifiers the value is a `Vec<Cpnt>`.
///
/// Returns a tuple `(arg1, arg2, ...)` of the bound positional values.
///
/// Spec ordering is validated at **compile time**: variadic specs (`*`, `+`)
/// must come last, and no required may follow an optional — an invalid
/// ordering is a build error. At runtime, if extra words remain after parsing
/// and no variadic spec is present, prints "too many arguments" to stderr and
/// returns `EX_USAGE`.
///
/// On error prints to stderr and returns `EX_USAGE` from the enclosing function.
#[macro_export]
macro_rules! parse_positionals {
    (
        $words_ptr:expr,
        [ $( $req:ident ),* $(,)? ]
        $( , [ $( $opt:ident ),* $(,)? ] )?
        $( , * $var_zero:ident )?
        $( , + $var_one:ident )?
    ) => {{
        // Compile-time validation
        const HAS_VARIADIC: bool = {
            const SPECS: &[$crate::bash_getopt::PositionalSpec] = &[
                $( $crate::bash_getopt::PositionalSpec::Required(stringify!($req)), )*
                $( $( $crate::bash_getopt::PositionalSpec::Optional(stringify!($opt)), )* )?
                $( $crate::bash_getopt::PositionalSpec::ZeroOrMore(stringify!($var_zero)), )?
                $( $crate::bash_getopt::PositionalSpec::OneOrMore(stringify!($var_one)), )?
            ];

            if let Some(err) = $crate::bash_getopt::validate_positional_specs(SPECS) {
                panic!("{}", err);
            }

            $crate::bash_getopt::has_variadic(SPECS)
        };

        let mut _words = unsafe {
            $crate::bash_api::WordListView::from_raw($words_ptr)
        }.into_iter();

        // 1. Required positional args
        $(
            let $req = match _words.next() {
                Some(val) => val,
                None => {
                    $crate::beprintln!("L_builtin: missing required argument");
                    return $crate::bash_api::EX_USAGE;
                }
            };
        )*

        // 2. Optional positional args
        $(
            $(
                let $opt = _words.next();
            )*
        )?

        // 3. Zero-or-more variadic (*files -> Vec<Cpnt>)
        $(
            let $var_zero = _words.by_ref().collect::<Vec<_>>();
        )?

        // 4. One-or-more variadic (+files -> Vec<Cpnt>)
        $(
            let $var_one = _words.by_ref().collect::<Vec<_>>();
            if $var_one.is_empty() {
                $crate::beprintln!("L_builtin: missing required argument");
                return $crate::bash_api::EX_USAGE;
            }
        )?

        // 5. Check for trailing extra arguments if non-variadic
        if !HAS_VARIADIC {
            if let Some(_) = _words.next() {
                $crate::beprintln!("L_builtin: too many arguments");
                return $crate::bash_api::EX_USAGE;
            }
        }

        // Tuple of bound variables
        (
            $( $req, )*
            $( $( $opt, )* )?
            $( $var_zero, )?
            $( $var_one, )?
        )
    }};
}

/// Parse options and positional arguments in one macro.
///
/// ```ignore
/// let (rest, src, files) = parse_args!(
///     args,
///     [ f => |_| force = true ],  // flags
///     [ o: => |val| output = Some(val) ],  // options with values
///     [src], +files  // required, one-or-more variadic
/// );
/// let (rest, src, mode, files) = parse_args!(
///     args,
///     [ f => || force = true ],
///     [ o: => |val| output = Some(val) ],
///     [src], [mode], *files  // required, optional, zero-or-more variadic
/// );
/// ```
///
/// First two arrays are flags and options for `getopts!`. The remaining
/// arguments follow `parse_positionals!` syntax.
#[macro_export]
macro_rules! parse_args {
    (
        $args:expr,
        [ $( $flag:tt )* ],
        [ $( $opt:tt )* ]
        $( , $( $pos:tt )* )?
    ) => {{
        let _rest = $crate::getopts!($args, [ $( $flag )* ], [ $( $opt )* ]);
        $crate::parse_positionals!(
            _rest
            $( , $( $pos )* )?
        )
    }};
}

/// Internal helper: call the action with or without the optarg.
#[macro_export]
macro_rules! bash_getopt2_call_action {
    // Value option (has colon): pass optarg
    ($action:expr, $optarg:expr, :) => {
        $action($optarg);
    };
    // Flag (no colon): call without argument
    ($action:expr, $optarg:expr,) => {
        $action();
    };
}
