#define _GNU_SOURCE 1

#include <assert.h>
#include <config.h>
#include <stdio.h>
#include <stdarg.h>
#include <string.h>

#include "bash_api.h"
#include "bash_loadables_gen.h" // generated by cmake

#define LEN(x) (sizeof(x) / sizeof((x)[0]))

#if defined(__GNUC__) || defined(__clang__)
#define SENTINEL __attribute__((sentinel))
#else
#define SENTINEL
#endif

static int compare_builtin(const void *key, const void *elem)
{
  const char *search_name = (const char *)key;
  const struct builtin *b = *(const struct builtin **)elem;
  return strcmp(search_name, b->name);
}

static struct builtin *find_loadable_builtin(const char *name)
{
  assert(name);
  size_t n = LEN(bash_loadables_gen);
  assert(n);
  struct builtin **match =
    (void *)bsearch(name, bash_loadables_gen, n, sizeof(struct builtin *), compare_builtin);
  return match ? *match : NULL;
}

static void print_loadables_usage(void)
{
  fprintf(
    stderr, "%s: usage: %s [-h] <subcommand> [args ...]\n", this_command_name, this_command_name
  );
  fprintf(stderr, "Available subcommands:\n");
  for (size_t i = 0; i < LEN(bash_loadables_gen); i++) {
    const struct builtin *b = bash_loadables_gen[i];
    assert(b);
    assert(b->name);
    assert(*b->name);
    fprintf(stderr, "  %-15s ", b->name);
    if (b->short_doc) {
      const char *nl = strchr(b->short_doc, '\n');
      if (nl) {
        /* Multi-line path: process line segments without per-char fputc */
        const char *p = b->short_doc;
        while (nl != NULL) {
          /* Print segment up to the newline */
          if (nl > p) {
            fwrite(p, 1, (size_t)(nl - p), stderr);
          }
          fputs("  ", stderr);
          /* Skip the newline and any leading whitespace following it */
          p = nl + 1;
          while (*p == ' ' || *p == '\t') {
            p++;
          }
          nl = strchr(p, '\n');
        }
        /* Print remaining trailing text after the final newline */
        if (*p != '\0') {
          fputs(p, stderr);
        }
      } else {
        /* Happy path: no newlines, print entire string directly */
        fputs(b->short_doc, stderr);
      }
    }
    fputc('\n', stderr);
  }
}

/// This is unreachable.
static const char *const ext_doc[] = {"", NULL};

int l_cmd_ext(WORD_LIST *list)
{
  int opt;
  l_enter_subcommand("ext", "SUBCOMMAND [args...]", ext_doc);
  reset_internal_getopt();
  while ((opt = internal_getopt(list, "h")) != -1) {
    switch (opt) {
    case 'h':
    case GETOPT_HELP:
      print_loadables_usage();
      return 0;
    default:
      print_loadables_usage();
      return (EX_USAGE);
    }
  }
  list = loptend;
  /* No subcommand provided */
  if (list == NULL) {
    builtin_error("no subcommand provided");
    print_loadables_usage();
    return (EX_USAGE);
  }
  const char *subcmd = list->word->word;
  assert(subcmd);
  struct builtin *b = find_loadable_builtin(subcmd);
  if (!b) {
    builtin_error("unknown subcommand `%s'", subcmd);
    print_loadables_usage();
    return (EX_USAGE);
  }
  assert(b->function);
  l_enter_subcommand(subcmd, b->short_doc, (void *)b->long_doc);
  // Hijack the -h --help to print full long documentation of the child subcommand.
  if (list->next && list->next->word) {
    const char *first = list->next->word->word;
    if (first) {
      if (strcmp(first, "--help") == 0 || strcmp(first, "-h") == 0) {
        l_builtin_usage_long();
        return 0;
      }
    }
  }
  return b->function(list);
}
