#define _GNU_SOURCE 1

#include <assert.h>
#include <config.h>
#include <stdio.h>
#include <stdarg.h>
#include <string.h>

#include <builtins.h>
#include <shell.h>
#include <common.h>
#include <bashgetopt.h>

#include "bash_api.h"
#include "bash_loadables_gen.h" // generated by cmake

#define LEN(x) (sizeof(x) / sizeof((x)[0]))
extern char *this_command_name;
extern int capture_subcommand(WORD_LIST*);

#if defined(__GNUC__) || defined(__clang__)
#define SENTINEL __attribute__((sentinel))
#else
#define SENTINEL
#endif

static SENTINEL char *aconcat(const char *first, ...)
{
  if (!first)
    return NULL;
  size_t len = strlen(first);
  va_list args;
  va_start(args, first);
  const char *arg = va_arg(args, const char *);
  while (arg != NULL) {
    len += strlen(arg);
    arg = va_arg(args, const char *);
  }
  va_end(args);
  char *result = l_xmalloc(len + 1);
  if (!result)
    return NULL;
  strcpy(result, first);
  va_start(args, first);
  arg = va_arg(args, const char *);
  while (arg != NULL) {
    strcat(result, arg);
    arg = va_arg(args, const char *);
  }
  va_end(args);
  return result;
}

static int compare_builtin(const void *key, const void *elem)
{
  const char *search_name = (const char *)key;
  const struct builtin *b = *(const struct builtin **)elem;
  return strcmp(search_name, b->name);
}

static struct builtin *find_loadable_builtin(const char *name)
{
  assert(name);
  size_t n = LEN(bash_loadables_gen);
  assert(n);
  struct builtin **match =
    (void *)bsearch(name, bash_loadables_gen, n, sizeof(struct builtin *), compare_builtin);
  return match ? *match : NULL;
}

static void print_loadables_usage(void)
{
  fprintf(stderr, "loadables: usage: loadables [-v <var>] [-h] <subcommand> [args ...]\n");
  fprintf(stderr, "Available subcommands:\n");
  for (size_t i = 0; i < LEN(bash_loadables_gen); i++) {
    const struct builtin *b = bash_loadables_gen[i];
    assert(b);
    assert(b->name);
    assert(*b->name);
    fprintf(stderr, "  %-15s ", b->name);
    if (b->short_doc) {
      const char *nl = strchr(b->short_doc, '\n');
      if (nl) {
        /* Multi-line path: process line segments without per-char fputc */
        const char *p = b->short_doc;
        while (nl != NULL) {
          /* Print segment up to the newline */
          if (nl > p) {
            fwrite(p, 1, (size_t)(nl - p), stderr);
          }
          fputs("  ", stderr);
          /* Skip the newline and any leading whitespace following it */
          p = nl + 1;
          while (*p == ' ' || *p == '\t') {
            p++;
          }
          nl = strchr(p, '\n');
        }
        /* Print remaining trailing text after the final newline */
        if (*p != '\0') {
          fputs(p, stderr);
        }
      } else {
        /* Happy path: no newlines, print entire string directly */
        fputs(b->short_doc, stderr);
      }
    }
    fputc('\n', stderr);
  }
}

static void l_builtin_long_usage(void)
{
  if (this_command_name && *this_command_name) {
    fprintf(stderr, "%s: usage: ", this_command_name);
  }
  if (current_builtin->short_doc) {
    fprintf(stderr, "%s\n", current_builtin->short_doc);
  }
  if (current_builtin->long_doc) {
    fprintf(stderr, "\n");
    for (char **i = (char **)current_builtin->long_doc; *i; i++) {
      fprintf(stderr, "%s\n", *i);
    }
  }
  fflush(stderr);
}

int l_cmd_ext(WORD_LIST *list)
{
  int opt;
  reset_internal_getopt();
  char *var = 0;
  while ((opt = internal_getopt(list, "hb:")) != -1) {
    switch (opt) {
      case 'v': var = list_optarg; break;
      case 'h':
      case GETOPT_HELP:
        print_loadables_usage();
        return (EX_USAGE);
      default:
        print_loadables_usage();
        return (EX_USAGE);
    }
  }
  list = loptend;
  /* No subcommand provided */
  if (list == NULL) {
    builtin_error("no subcommand provided");
    print_loadables_usage();
    return (EX_USAGE);
  }
  const char *subcmd = list->word->word;
  assert(subcmd);
  struct builtin *b = find_loadable_builtin(subcmd);
  if (!b) {
    builtin_error("unknown subcommand `%s'", subcmd);
    print_loadables_usage();
    return (EXECUTION_FAILURE);
  }
  assert(b->function);
  //
  l_xfree(this_command_name);
  this_command_name = aconcat("L_builtin ", " ", subcmd, NULL);
  current_builtin = b;
  //
  // WORD_LIST head;
  // head.next = list;
  // head.word = &(WORD_DESC){var, 0};
  // list = list->next;
  //
  const char *first = list->word->word;
  if (strcmp(first, "--help") == 0 || strcmp(first, "-h") == 0) {
    l_builtin_long_usage();
    return (EX_USAGE);
  }
  return b->function(list);
}
