# Function to create bash loadables target
# Arguments:
#   TARGET_NAME: base name for the target (creates ${TARGET_NAME})
#   BASH_SOURCE: path to bash source
#   GENERATED_DIR: directory for generated header
function(create_bash_loadables_target TARGET_NAME BASH_SOURCE GENERATED_DIR)
    # Gather loadable source files
    file(GLOB sources CONFIGURE_DEPENDS SORT_BY MODIFY ORDER DESCENDING "${BASH_SOURCE}/examples/loadables/*.c")
    set(loadable_names "")
    set(valid_sources "")
    set(excluded_sources "")
    foreach(src ${sources})
        get_filename_component(src_name "${src}" NAME)
        if(src_name IN_LIST excluded_sources)
            continue()
        endif()
        file(READ "${src}" src_content)
        set(regex "struct[ \t]+builtin[ \t]+([A-Za-z0-9_]+)")
        string(REGEX MATCHALL "${regex}" matched_structs "${src_content}")
        if(matched_structs)
            set(file_has_conflict FALSE)
            set(file_struct_names "")
            foreach(match ${matched_structs})
                string(REGEX REPLACE "${regex}" "\\1" struct_name "${match}")
                if(struct_name IN_LIST loadable_names)
                    set(file_has_conflict TRUE)
                    break()
                endif()
                list(APPEND file_struct_names "${struct_name}")
            endforeach()
            if(file_has_conflict)
                message(STATUS "Skipping older/duplicate source: ${src}")
            else()
                list(APPEND valid_sources "${src}")
                list(APPEND loadable_names ${file_struct_names})
            endif()
        else()
            message(WARNING "Skipping ${src}: no symbol matching '${regex}' found")
        endif()
    endforeach()
    # Check for duplicates in loadable_names
    set(temp "${loadable_names}")
    list(REMOVE_DUPLICATES temp)
    list(LENGTH loadable_names len_orig)
    list(LENGTH temp len_dedup)
    if(NOT len_orig EQUAL len_dedup)
        message(FATAL_ERROR "Assertion failed: Duplicate builtin struct registered across loadable sources (found duplicates in loadable_names)")
    endif()
    # Check for duplicates in valid_sources
    set(temp "${valid_sources}")
    list(REMOVE_DUPLICATES temp)
    list(LENGTH valid_sources len_orig)
    list(LENGTH temp len_dedup)
    if(NOT len_orig EQUAL len_dedup)
        message(FATAL_ERROR "Assertion failed: Duplicate builtin files found (found duplicates in valid_sources)")
    endif()
    list(SORT loadable_names)
    list(LENGTH loadable_names loadable_count)
    string(JOIN " " loadable_names_str ${loadable_names})
    message(STATUS "Found ${loadable_count} bash loadables: ${loadable_names_str}")
    set(c_content "/* Automatically generated by CMake. Do not edit. */\n\n#include <builtins.h>\n\n")
    foreach(name ${loadable_names})
        string(APPEND c_content "extern const struct builtin ${name};\n")
    endforeach()
    string(APPEND c_content "\nstatic const struct builtin *const bash_gen[] = {\n")
    foreach(name ${loadable_names})
        string(APPEND c_content "    &${name},\n")
    endforeach()
    string(APPEND c_content "};\n")
    file(CONFIGURE OUTPUT "${GENERATED_DIR}/bash_gen.h" CONTENT "${c_content}" @ONLY)
    add_library(${TARGET_NAME} OBJECT ${valid_sources})
    set_target_properties(${TARGET_NAME} PROPERTIES
        POSITION_INDEPENDENT_CODE ON
    )
    target_compile_options(${TARGET_NAME} PRIVATE
        -ffunction-sections
        -fdata-sections
        -Wno-discarded-qualifiers
        -Wno-parentheses
        -Wno-unused-variable
        -Wno-unused-parameter
        -Wno-sign-compare
        -Wno-implicit-fallthrough
        -Wno-format-security
        -Wno-unused-but-set-variable
        -Wno-implicit-function-declaration
        -w
    )
    target_include_directories(${TARGET_NAME} INTERFACE "${GENERATED_DIR}")
endfunction()
