name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  BASHES: "5.3"

jobs:
  build-test-publish:
    name: Build, Test, Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build, Test, Output
        uses: docker/build-push-action@v5
        with:
          context: .
          target: output
          push: false
          build-args: |
            BASHES=${{ env.BASHES }}
            MAKEARGS=
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=local,dest=/tmp/build-output

      - name: Upload L_builtin.so artifacts
        uses: actions/upload-artifact@v4
        with:
          name: L_builtin-artifacts
          path: /tmp/build-output/output/**/L_builtin.so
