name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-publish:
    name: Build, Test, Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build, Test, Output
        uses: docker/build-push-action@v7
        with:
          context: .
          # target: output
          target: build-output
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=local,dest=/tmp/build-output

      - name: Upload L_builtin.so artifacts
        uses: actions/upload-artifact@v7
        with:
          name: L_builtin-artifacts
          path: /tmp/build-output/**
